name: SiriusOS

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ pc ]
  pull_request:
    branches: [ pc ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-os:
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Ubuntu Dependencies
        run: |
          sudo add-apt-repository ppa:dotnet/backports
          sudo apt update
          sudo apt install -y make yasm xorriso dotnet-sdk-6.0 git grub-mkrescue mtools
          git clone https://github.com/CosmosOS/Cosmos.git
          cd Cosmos
          make
          cd ..
          wget https://github.com/PratyushKing/cosmosCLI/releases/download/v1.3.1-stable/cosmos.deb
          sudo dpkg -i cosmos.deb
      
      - name: Build SiriusOS
        run: |
          sh make.sh
          
      - name: Upload image
        uses: actions/upload-artifact@v3
        with:
          name: Disk Image
          path: SiriusOS.iso