name: SiriusOS x86

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      date:
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-os:
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Install Ubuntu Dependencies
        run: |
          sudo add-apt-repository ppa:dotnet/backports
          sudo apt update
          sudo apt install -y make yasm xorriso dotnet-sdk-6.0 git grub-common grub-pc-bin mtools
          git clone https://github.com/CosmosOS/Cosmos.git
          cd Cosmos
          make
          cd ..
          wget https://github.com/PratyushKing/cosmosCLI/releases/download/v1.3.1-stable/cosmos.deb
          sudo dpkg -i cosmos.deb
      
      - name: Build SiriusOS
        run: |
          sh make.sh
          
      - name: Upload image
        uses: actions/upload-artifact@v3
        with:
          name: Disk Image
          path: SiriusOS.iso
  
  release:
    runs-on: ubuntu-latest
    needs: [build-os]

    steps:
    - uses: actions/download-artifact@v3
      
    - name: release
      uses: softprops/action-gh-release@v2.0.8
      with:
        name: SiriusOS Nightly ${{ inputs.date }}
        tag_name: ${{ inputs.date }}
        draft: false
        files: '**/*.iso'
        body: |
          * ⚠️ This build was builded on github actions not on maintainers machine!